### PR TITLE
fix: skip URL encoding for S3 disk to prevent double encoding

### LINKED ISSUE #3933: Fix double encoding of percent signs in filenames when using S3 disk
## Problem
The fix in #3930 introduced a regression for S3 disks.

When a filename contains `%` (e.g. `IMG_5405%20copy.jpg`), the URL comes out 
triple-encoded on S3: IMG_5405%252520copy.jpg

This happens because the S3 SDK already encodes URLs internally, so our `rawurlencode()` on top causes double encoding.

Local disk is fine, only S3 is affected.

## Proposed Fix
Skip encoding in `getUrlEncodedPathRelativeToRoot()` when the disk driver is `s3`.

### PR DESCRIPTION
**Pull request by moemadeldin**
Fixes #3933

### CODE REVIEW

File: src/Support/UrlGenerator/BaseUrlGenerator.php [hunk 1]
```diff
@@ -73,6 +73,12 @@ protected function getDisk(): Filesystem
 
     protected function getUrlEncodedPathRelativeToRoot(): string
     {
+        $driver = config("filesystems.disks.{$this->getDiskName()}.driver");
+        
+        if ($driver === 's3') {
```
Comment (francoism90) [inline src/Support/UrlGenerator/BaseUrlGenerator.php]: Hmm, what if you did a local check instead? Laravel does support additional fs drivers, I don't know if they also should be skipped?

Comment (moemadeldin) [reply src/Support/UrlGenerator/BaseUrlGenerator.php]: switched to checking for `local` instead.

**Comment by freekmurze** [comment]
Thanks!
